project:
  type: website

website:
  title: "Notas PAU CV"
  navbar:
    left:
      - href: index.qmd
        text: Normal
      - about.qmd
      - shiny.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



